var annotated =
[
    [ "File", "namespace_file.html", null ],
    [ "AcademicUser", "class_academic_user.html", "class_academic_user" ],
    [ "ActionCanceled", "class_action_canceled.html", "class_action_canceled" ],
    [ "ByteBuffer", "class_byte_buffer.html", "class_byte_buffer" ],
    [ "ByteBufferException", "class_byte_buffer_exception.html", null ],
    [ "ConsoleWritePolicy", "struct_console_write_policy.html", "struct_console_write_policy" ],
    [ "EnterpriseUser", "class_enterprise_user.html", "class_enterprise_user" ],
    [ "EOFCharacterValue", "class_e_o_f_character_value.html", "class_e_o_f_character_value" ],
    [ "FileWritePolicy", "struct_file_write_policy.html", "struct_file_write_policy" ],
    [ "GridManager", "class_grid_manager.html", "class_grid_manager" ],
    [ "IMenu", "class_i_menu.html", "class_i_menu" ],
    [ "InvalidValue", "class_invalid_value.html", "class_invalid_value" ],
    [ "IPrint", "class_i_print.html", "class_i_print" ],
    [ "ISave", "class_i_save.html", "class_i_save" ],
    [ "IUpdate", "class_i_update.html", "class_i_update" ],
    [ "Job", "class_job.html", "class_job" ],
    [ "Loader", "class_loader.html", "class_loader" ],
    [ "Logger", "class_logger.html", "class_logger" ],
    [ "Machine", "class_machine.html", "class_machine" ],
    [ "MachineInExecution", "class_machine_in_execution.html", "class_machine_in_execution" ],
    [ "Menu", "class_menu.html", "class_menu" ],
    [ "ParentNULL", "class_parent_n_u_l_l.html", "class_parent_n_u_l_l" ],
    [ "Runnable", "class_runnable.html", "class_runnable" ],
    [ "Saver", "class_saver.html", "class_saver" ],
    [ "Software", "class_software.html", "class_software" ],
    [ "User", "class_user.html", "class_user" ],
    [ "Writer", "struct_writer.html", "struct_writer" ]
];